// Fall 2026 — Binghamton University course data, extracted from uploaded syllabi.
// All dates are ISO (YYYY-MM-DD). Times are 24h "HH:MM" or null for all-day/unspecified.

const COURSES = [
  {
    id: "futures",
    code: "ENG 180J",
    name: "Futures Past",
    instructor: "Prof. Glovinsky / Hannah Licht",
    meets: "Tue/Thu 9:45–11:15am",
    room: "Classroom Wing 109",
    color: "#c17d2c",
    textbooks: [
      "Thomas More, Utopia (1516), Penguin Classics, trans. Turner — ISBN 9780140449105",
      "Mary Shelley, Frankenstein (1818), Oxford World's Classics, ed. Groom — ISBN 9780198840824",
      "William Morris, News from Nowhere (1890), Penguin Classics, ed. Wilmer — ISBN 9780140433302",
      "H. G. Wells, The Time Machine (1895), Signet Classics — ISBN 978-0451528551",
      "Aldous Huxley, Brave New World (1932), Harper Perennial — ISBN 9780060850524",
      "Philip K. Dick, Do Androids Dream of Electric Sheep? (1968), Del Rey — ISBN 978-0345404473",
      "Octavia E. Butler, Bloodchild and Other Stories (1984), Seven Stories Press — ISBN 978-1583226988",
      "(All other readings are posted as PDFs on Brightspace.)",
    ],
  },
  {
    id: "aaas",
    code: "AAAS 280B",
    name: "Asian American Digital Culture",
    instructor: "Prof. Muhammad Waqar Azeem",
    meets: "Wed/Fri 9:45–11:15am",
    room: "Rockefeller Center 259",
    color: "#2c8c86",
    textbooks: [
      "No print textbook — critical readings are posted on Brightspace, including:",
      "Data Empire by Roopika Risam (selections)",
      "Asian America.Net: Ethnicity, Nationalism, and Cyberspace, ed. Rachel C. Lee & Sau-ling C. Wong (Introduction)",
      "Digitizing Race: Visual Cultures of the Internet by Lisa Nakamura (selections)",
      "\"Political Inequality in the Digital World\" by N. K. Chan",
      "\"Asian America Gone Viral\" by Lori Kido Lopez, in The Routledge Companion to Asian American Media",
    ],
  },
  {
    id: "plsc",
    code: "PLSC 113",
    name: "Intro to Comparative Politics",
    instructor: "Prof. Robin E. Best",
    meets: "Tue/Thu 11:45am–1:15pm",
    room: "Lecture Hall 1",
    color: "#8c3b3b",
    textbooks: [
      "Clark, William Roberts, Matt Golder, and Sona Nadenichek Golder. 2024. Principles of Comparative Politics, 4th Edition. Washington, D.C.: CQ Press.",
    ],
  },
  {
    id: "psyc",
    code: "PSYC 223",
    name: "Behavior Disorders",
    instructor: "Prof. Richard E. Mattson",
    meets: "Mon/Wed/Fri 2:45–3:45pm",
    room: "LH 014",
    color: "#5b4b8a",
    textbooks: [
      "Craighead, W. E. (2017). Psychopathology: History, Diagnosis, and Empirical Foundations (3rd Ed.). John Wiley & Sons.",
      "Oltmanns, T. F., Martin, M. T., & Neale, J. M. (2011). Case Studies in Abnormal Psychology (11th Ed.). John Wiley & Sons.",
      "(Individual readings in the schedule below, e.g. \"Craighead 3\" or \"Oltmanns 7,\" refer to chapters/case studies in these two books.)",
    ],
  },
];

// type: "assignment" | "exam" | "reading" | "note" (schedule quirk / break / no-class)
const EVENTS = [
  // ---------------- Futures Past (ENG 180J) ----------------
  { course: "futures", date: "2026-08-18", type: "note", title: "Introduction: Histories of the Future", detail: "" },
  { course: "futures", date: "2026-08-20", type: "assignment", title: "Start-of-Semester Survey due", detail: "Source Project survey, due before class." },
  { course: "futures", date: "2026-08-20", type: "reading", title: "Thomas More, Utopia (1516), pp. 7–47 (Letters and Book 1)", detail: "Unit: Inventing Utopia." },
  { course: "futures", date: "2026-08-25", type: "reading", title: "Thomas More, Utopia (1516), pp. 48–113 (Book 2)", detail: "Also: George Orwell, \"Can Socialists Be Happy?\" (1943)." },
  { course: "futures", date: "2026-08-27", type: "reading", title: "Mary Shelley, Frankenstein (1818), Vol. 1 (pp. 3–77)", detail: "Unit: Origins of Science Fiction." },
  { course: "futures", date: "2026-09-01", type: "reading", title: "Mary Shelley, Frankenstein (1818), Vol. 2 (pp. 81–141)", detail: "Also: Darko Suvin, \"On the Poetics of the Science Fiction Genre\" (1972)." },
  { course: "futures", date: "2026-09-03", type: "reading", title: "Mary Shelley, Frankenstein (1818), Vol. 3 (pp. 145–216)", detail: "Also: Georges Méliès, A Trip to the Moon (1902)." },
  { course: "futures", date: "2026-09-08", type: "note", title: "Monday classes meet (not Tuesday)", detail: "Schedule quirk — attend as a Monday." },
  { course: "futures", date: "2026-09-10", type: "reading", title: "Chris Jennings, Paradise Now, Ch. 2 \"New Harmony\"", detail: "Unit: Ideal Societies. Also: Robert Owen, \"A Sketch of Some of the Errors and Evils Arising from the Past and Present State of Society\" (1817)." },
  { course: "futures", date: "2026-09-13", type: "assignment", title: "Paper 1 due", detail: "5 pages incl. MLA bibliography. Due by 11:59pm." },
  { course: "futures", date: "2026-09-15", type: "reading", title: "Charles Fourier, The Utopian Vision of Charles Fourier (selections)", detail: "\"The Ideal Community,\" \"Attractive Work,\" \"The New Amorous World.\" Also: McKenzie Wark, \"Charles Fourier's Queer Theory.\"" },
  { course: "futures", date: "2026-09-17", type: "reading", title: "Samuel Butler, \"The Book of the Machines,\" Erewhon (1872)", detail: "Unit: After the Revolution." },
  { course: "futures", date: "2026-09-22", type: "reading", title: "William Morris, News from Nowhere (1890)", detail: "" },
  { course: "futures", date: "2026-09-24", type: "reading", title: "William Morris, News from Nowhere (1890) (cont.)", detail: "" },
  { course: "futures", date: "2026-09-29", type: "reading", title: "H. G. Wells, The Time Machine (1895)", detail: "" },
  { course: "futures", date: "2026-10-01", type: "reading", title: "H. G. Wells, The Time Machine (1895) (cont.)", detail: "" },
  { course: "futures", date: "2026-10-04", type: "assignment", title: "Rewrite of Paper 1 due", detail: "Thorough rewrite based on professor feedback." },
  { course: "futures", date: "2026-10-06", type: "reading", title: "E. M. Forster, \"The Machine Stops\" (1909)", detail: "Unit: Brave New Worlds." },
  { course: "futures", date: "2026-10-08", type: "exam", title: "Passage Identification Midterm Exam", detail: "In class." },
  { course: "futures", date: "2026-10-13", type: "note", title: "Fall Break — no class", detail: "" },
  { course: "futures", date: "2026-10-15", type: "note", title: "Fall Break — no class", detail: "" },
  { course: "futures", date: "2026-10-20", type: "reading", title: "W. E. B. Du Bois, \"The Comet\" (1920)", detail: "" },
  { course: "futures", date: "2026-10-22", type: "note", title: "Library Instructional Session (Matthew Harrick)", detail: "" },
  { course: "futures", date: "2026-10-22", type: "reading", title: "Fritz Lang, Metropolis (1927)", detail: "" },
  { course: "futures", date: "2026-10-27", type: "note", title: "Special Collections Visit / Campus Tour (grouped)", detail: "Group 1: Special Collections. Group 2: Self-guided tour." },
  { course: "futures", date: "2026-10-27", type: "reading", title: "Le Corbusier, \"The Street\"; Lewis Mumford, \"Yesterday's City of Tomorrow\"", detail: "Both groups read this for Oct 27 & 29." },
  { course: "futures", date: "2026-10-29", type: "note", title: "Special Collections Visit / Campus Tour (grouped)", detail: "Group 1: Self-guided tour. Group 2: Special Collections." },
  { course: "futures", date: "2026-10-30", type: "assignment", title: "Paper 2 due", time: "17:00", detail: "6 pages incl. MLA bibliography. Due 5:00pm." },
  { course: "futures", date: "2026-11-03", type: "reading", title: "Aldous Huxley, Brave New World (1932), chs. 1–6, pp. 3–106", detail: "" },
  { course: "futures", date: "2026-11-05", type: "reading", title: "Aldous Huxley, Brave New World (1932), chs. 7–11, pp. 107–170", detail: "" },
  { course: "futures", date: "2026-11-10", type: "reading", title: "Aldous Huxley, Brave New World (1932), chs. 12–18, pp. 171–259", detail: "" },
  { course: "futures", date: "2026-11-12", type: "reading", title: "Ayn Rand, Anthem (1938)", detail: "" },
  { course: "futures", date: "2026-11-17", type: "reading", title: "Isaac Asimov, \"Reason\" (1941), \"Runaround\" (1942)", detail: "Unit: The Posthuman." },
  { course: "futures", date: "2026-11-19", type: "reading", title: "Philip K. Dick, Do Androids Dream of Electric Sheep? (1968), chs. 1–8, pp. 3–89", detail: "" },
  { course: "futures", date: "2026-11-24", type: "note", title: "Friday classes meet", detail: "Schedule quirk." },
  { course: "futures", date: "2026-11-26", type: "note", title: "No class — Thanksgiving", detail: "" },
  { course: "futures", date: "2026-12-01", type: "reading", title: "Philip K. Dick, Do Androids Dream of Electric Sheep? (1968), chs. 9–22, pp. 90–224", detail: "" },
  { course: "futures", date: "2026-12-03", type: "reading", title: "Octavia Butler, Bloodchild and Other Stories: \"Bloodchild,\" \"The Evening and the Morning and the Night\" (pp. 3–68)", detail: "" },
  { course: "futures", date: "2026-12-08", type: "reading", title: "Octavia Butler, \"The Book of Martha\" (pp. 189–213)", detail: "Also: Ursula Le Guin, \"The Ones Who Walk Away from Omelas\" (1973, 4 pp)." },
  { course: "futures", date: "2026-12-11", type: "assignment", title: "Exploratory Paper & Annotated Bibliography due", detail: "9 pages. MLA or Chicago bibliography." },
  { course: "futures", date: "2026-12-15", type: "exam", title: "Final Exam (date TBA — placeholder)", detail: "Prof. will announce exact date; update once known." },

  // ---------------- Asian American Digital Culture (AAAS 280B) ----------------
  { course: "aaas", date: "2026-08-19", type: "note", title: "Icebreaker", detail: "Session 1." },
  { course: "aaas", date: "2026-08-21", type: "note", title: "Syllabus", detail: "Session 2." },
  { course: "aaas", date: "2026-08-26", type: "reading", title: "Asian Americans (PBS documentary), Ep. 1", detail: "Session 3." },
  { course: "aaas", date: "2026-08-28", type: "reading", title: "Asian Americans (PBS documentary), Ep. 1 (cont.)", detail: "Session 4." },
  { course: "aaas", date: "2026-09-02", type: "reading", title: "Asian America.Net: Ethnicity, Nationalism, and Cyberspace (Introduction)", detail: "Session 5. Ed. Rachel C. Lee & Sau-ling C. Wong." },
  { course: "aaas", date: "2026-09-04", type: "reading", title: "\"Uploaded: The Asian American Movement\" (documentary)", detail: "Session 6." },
  { course: "aaas", date: "2026-09-09", type: "reading", title: "\"Uploaded: The Asian American Movement\" (documentary), cont.", detail: "Session 7." },
  { course: "aaas", date: "2026-09-11", type: "note", title: "No class — Rosh Hashanah", detail: "" },
  { course: "aaas", date: "2026-09-16", type: "reading", title: "Digitizing Race: Visual Cultures of the Internet (selections)", detail: "Session 8. By Lisa Nakamura." },
  { course: "aaas", date: "2026-09-18", type: "exam", title: "Quiz", detail: "In class." },
  { course: "aaas", date: "2026-09-18", type: "reading", title: "\"Reappropriate\" by Jenn Fang", detail: "Session 9." },
  { course: "aaas", date: "2026-09-23", type: "reading", title: "\"Reappropriate\" by Jenn Fang (cont.)", detail: "Session 10." },
  { course: "aaas", date: "2026-09-25", type: "reading", title: "\"Political Inequality in the Digital World: The Puzzle of Asian American Political Participation\"", detail: "Session 11. By N. K. Chan." },
  { course: "aaas", date: "2026-09-30", type: "reading", title: "\"Political Inequality in the Digital World\" (cont.)", detail: "Session 12. By N. K. Chan." },
  { course: "aaas", date: "2026-10-02", type: "reading", title: "\"Self Evident: Asian America's Stories\" (podcast)", detail: "Session 13." },
  { course: "aaas", date: "2026-10-07", type: "assignment", title: "Short Midterm Paper due", detail: "4–5 pages, analyzing a component of Asian American digital culture." },
  { course: "aaas", date: "2026-10-07", type: "reading", title: "\"Self Evident: Asian America's Stories\" (cont.)", detail: "Session 14." },
  { course: "aaas", date: "2026-10-09", type: "reading", title: "Asian American Arts Alliance (digital project)", detail: "Session 15." },
  { course: "aaas", date: "2026-10-10", type: "note", title: "Fall Break — no classes (through 10/18)", detail: "" },
  { course: "aaas", date: "2026-10-21", type: "reading", title: "Asian American Arts Alliance (cont.)", detail: "Session 16." },
  { course: "aaas", date: "2026-10-23", type: "reading", title: "Asian American Arts Alliance (cont.)", detail: "Session 17." },
  { course: "aaas", date: "2026-10-28", type: "reading", title: "South Asian American Digital Archive (SAADA)", detail: "Session 18." },
  { course: "aaas", date: "2026-10-30", type: "reading", title: "\"Asian America Gone Viral: A Genealogy of Asian American YouTubers and Memes\"", detail: "Session 19. By Lori Kido Lopez, in The Routledge Companion to Asian American Media." },
  { course: "aaas", date: "2026-11-04", type: "reading", title: "Asian American Writers' Workshop (AAWW) — Poetry", detail: "Session 20. Selected literary texts." },
  { course: "aaas", date: "2026-11-06", type: "assignment", title: "Digital Content Creation due", detail: "Turn midterm paper into a digital project (podcast, webpage, etc.)." },
  { course: "aaas", date: "2026-11-06", type: "reading", title: "Data Empire (selections)", detail: "Session 21. By Roopika Risam." },
  { course: "aaas", date: "2026-11-11", type: "note", title: "Student Presentations", detail: "Session 22." },
  { course: "aaas", date: "2026-11-13", type: "note", title: "Student Presentations", detail: "Session 23." },
  { course: "aaas", date: "2026-11-18", type: "note", title: "Student Presentations", detail: "Session 24." },
  { course: "aaas", date: "2026-11-20", type: "note", title: "Student Presentations", detail: "Session 25." },
  { course: "aaas", date: "2026-11-25", type: "note", title: "Thanksgiving Break — no classes (through 11/29)", detail: "" },
  { course: "aaas", date: "2026-12-02", type: "note", title: "Final Paper Draft Review", detail: "Session 26." },
  { course: "aaas", date: "2026-12-04", type: "note", title: "Last class — Final Paper Draft Review", detail: "Session 27." },
  { course: "aaas", date: "2026-12-10", type: "assignment", title: "Final Paper due", detail: "8–10 pages, incl. literature review of 4 academic resources." },

  // ---------------- PLSC 113 — Intro to Comparative Politics ----------------
  // Reading schedule (topic + assigned chapters from Clark, Golder & Golder)
  { course: "plsc", date: "2026-08-18", type: "reading", title: "Ch. 1 — The Scientific Study of Politics I", detail: "Week 1 (Aug 18 & 20). No discussion sections this week." },
  { course: "plsc", date: "2026-08-25", type: "reading", title: "Ch. 2 — The Scientific Study of Politics II", detail: "Week 2 (Aug 25 & 27)." },
  { course: "plsc", date: "2026-09-01", type: "reading", title: "Ch. 3 — The Modern Nation-State", detail: "Week 3 (Sept 1 & 3)." },
  { course: "plsc", date: "2026-09-08", type: "note", title: "Monday classes meet (not Tuesday)", detail: "" },
  { course: "plsc", date: "2026-09-08", type: "reading", title: "Ch. 4 — The Modern Nation-State (cont.)", detail: "Week 4 (Sept 8 & 10)." },
  { course: "plsc", date: "2026-09-15", type: "note", title: "Review for Exam I", detail: "Week 5 — review Sept 15, Exam I on Sept 17." },
  { course: "plsc", date: "2026-09-17", type: "exam", title: "Exam I", detail: "Multiple choice + short answer, non-cumulative." },
  { course: "plsc", date: "2026-09-22", type: "reading", title: "Ch. 5 — Measuring Democracy I", detail: "Week 6 (Sept 22 & 24)." },
  { course: "plsc", date: "2026-09-29", type: "reading", title: "Ch. 6 & 7 — Determinants of Democracy I", detail: "Week 7 (Sept 29 & Oct 1)." },
  { course: "plsc", date: "2026-10-06", type: "reading", title: "Ch. 8 — Determinants of Democracy II", detail: "Week 8 (Oct 6 & 8)." },
  { course: "plsc", date: "2026-10-13", type: "note", title: "Fall Break — no class", detail: "" },
  { course: "plsc", date: "2026-10-15", type: "note", title: "Fall Break — no class", detail: "" },
  { course: "plsc", date: "2026-10-20", type: "reading", title: "Ch. 9 — Dictatorships", detail: "Week 10 (Oct 20 & 22)." },
  { course: "plsc", date: "2026-10-27", type: "note", title: "Review for Exam 2", detail: "Week 11 — review Oct 27, Exam 2 on Oct 29." },
  { course: "plsc", date: "2026-10-29", type: "exam", title: "Exam 2", detail: "Multiple choice + short answer, non-cumulative." },
  { course: "plsc", date: "2026-11-03", type: "reading", title: "Ch. 10 — Group Decision-Making", detail: "Week 12 (Nov 3 & 5)." },
  { course: "plsc", date: "2026-11-11", type: "reading", title: "Ch. 12 & 13 — Party Systems & Electoral Systems", detail: "Week 13, listed as Nov 11 & 13 in the syllabus schedule." },
  { course: "plsc", date: "2026-11-17", type: "reading", title: "Ch. 11 — Presidents and Parliaments", detail: "Week 14 (Nov 17 & 19)." },
  { course: "plsc", date: "2026-11-24", type: "note", title: "No class — Friday classes meet instead", detail: "" },
  { course: "plsc", date: "2026-11-26", type: "note", title: "No class — Thanksgiving Break", detail: "" },
  { course: "plsc", date: "2026-12-01", type: "reading", title: "Ch. 14 & 15 — Consequences of Democracy/Dictatorship", detail: "Week 16 (Dec 1 & 3)." },
  { course: "plsc", date: "2026-12-08", type: "note", title: "Review day", detail: "Week 17 — review before Exam #3." },
  { course: "plsc", date: "2026-12-15", type: "exam", title: "Exam #3 (date TBA — placeholder)", detail: "Held during scheduled final-exam period; update once announced." },

  // ---------------- PSYC 223 — Behavior Disorders ----------------
  { course: "psyc", date: "2026-08-19", type: "note", title: "Introduction, Defining Behavior Disorders", detail: "Class #1." },
  { course: "psyc", date: "2026-08-21", type: "reading", title: "Defining Behavior Disorders", detail: "Class #2. Reading: Craighead 1." },
  { course: "psyc", date: "2026-08-24", type: "note", title: "History of Classification and Diagnosis", detail: "Class #3." },
  { course: "psyc", date: "2026-08-26", type: "reading", title: "History of Classification and Diagnosis", detail: "Class #4. Reading: Widiger & Sankis, 2000 (377–384 first paragraph; 390–398 last paragraph)." },
  { course: "psyc", date: "2026-08-28", type: "note", title: "History of Classification and Diagnosis", detail: "Class #5." },
  { course: "psyc", date: "2026-08-31", type: "note", title: "Introduction to Anxiety Disorders", detail: "Class #6." },
  { course: "psyc", date: "2026-09-02", type: "note", title: "Introduction to Anxiety Disorders/Specific Phobias", detail: "Class #7." },
  { course: "psyc", date: "2026-09-04", type: "note", title: "Specific Phobias", detail: "Class #8." },
  { course: "psyc", date: "2026-09-08", type: "note", title: "Class meets (Labor Day makeup)", detail: "Class #9." },
  { course: "psyc", date: "2026-09-08", type: "reading", title: "Panic", detail: "Class #9. Reading: Craighead 3, Oltmanns 7." },
  { course: "psyc", date: "2026-09-09", type: "note", title: "Panic", detail: "Class #10." },
  { course: "psyc", date: "2026-09-14", type: "note", title: "Panic", detail: "Class #11." },
  { course: "psyc", date: "2026-09-16", type: "reading", title: "Generalized Anxiety Disorder", detail: "Class #12. Reading: Craighead 4." },
  { course: "psyc", date: "2026-09-18", type: "note", title: "Generalized Anxiety Disorder", detail: "Class #13." },
  { course: "psyc", date: "2026-09-23", type: "note", title: "Generalized Anxiety Disorder", detail: "Class #14." },
  { course: "psyc", date: "2026-09-25", type: "exam", title: "Exam 1", detail: "Class #15. 25% of final grade." },
  { course: "psyc", date: "2026-09-28", type: "reading", title: "Obsessive Compulsive Disorder", detail: "Class #16. Reading: Craighead 5, Oltmanns 8." },
  { course: "psyc", date: "2026-09-30", type: "note", title: "Obsessive Compulsive Disorder", detail: "Class #17." },
  { course: "psyc", date: "2026-10-02", type: "reading", title: "Social Phobia", detail: "Class #18. Reading: Craighead 2." },
  { course: "psyc", date: "2026-10-05", type: "note", title: "Social Phobia", detail: "Class #19." },
  { course: "psyc", date: "2026-10-07", type: "reading", title: "Depression", detail: "Class #20. Reading: Nesse, 2000." },
  { course: "psyc", date: "2026-10-09", type: "note", title: "Depression", detail: "Class #21." },
  { course: "psyc", date: "2026-10-19", type: "reading", title: "Depression", detail: "Class #22. Reading: Oltmanns 6." },
  { course: "psyc", date: "2026-10-21", type: "reading", title: "Depression", detail: "Class #23. Reading: Craighead 7." },
  { course: "psyc", date: "2026-10-23", type: "reading", title: "Substance Use and Addiction", detail: "Class #24. Reading: Craighead 11." },
  { course: "psyc", date: "2026-10-26", type: "note", title: "Substance Use and Addiction", detail: "Class #25." },
  { course: "psyc", date: "2026-10-28", type: "reading", title: "Substance Use and Addiction", detail: "Class #26. Reading: Oltmanns 19." },
  { course: "psyc", date: "2026-10-30", type: "exam", title: "Exam 2", detail: "Class #27. 25% of final grade." },
  { course: "psyc", date: "2026-11-02", type: "reading", title: "Eating Disorders I", detail: "Class #28. Reading: Craighead 12." },
  { course: "psyc", date: "2026-11-04", type: "reading", title: "Eating Disorders I", detail: "Class #29. Reading: Craighead 8, Oltmanns 13." },
  { course: "psyc", date: "2026-11-06", type: "reading", title: "Eating Disorders II", detail: "Class #30. Reading: Oltmanns 14." },
  { course: "psyc", date: "2026-11-09", type: "reading", title: "Schizophrenia I", detail: "Class #31. Reading: Craighead 10." },
  { course: "psyc", date: "2026-11-11", type: "reading", title: "Schizophrenia II", detail: "Class #32. Reading: Oltmanns 3." },
  { course: "psyc", date: "2026-11-13", type: "note", title: "Schizophrenia III", detail: "Class #33." },
  { course: "psyc", date: "2026-11-16", type: "reading", title: "Bipolar Disorder/Hypomania", detail: "Class #34. Reading: Oltmanns 5." },
  { course: "psyc", date: "2026-11-18", type: "note", title: "Bipolar Disorder/Hypomania", detail: "Class #35." },
  { course: "psyc", date: "2026-11-20", type: "exam", title: "Exam 3", detail: "Class #36. 25% of final grade." },
  { course: "psyc", date: "2026-11-23", type: "reading", title: "Posttraumatic Stress Disorder I*", detail: "Class #37. Reading: Craighead 6. *Potentially triggering material — attendance optional per syllabus." },
  { course: "psyc", date: "2026-11-24", type: "note", title: "Class meets (Thanksgiving makeup)", detail: "Class #38." },
  { course: "psyc", date: "2026-11-24", type: "reading", title: "Posttraumatic Stress Disorder II*", detail: "Class #38. Reading: Oltmanns 10. *Potentially triggering material — attendance optional per syllabus." },
  { course: "psyc", date: "2026-11-30", type: "reading", title: "Personality Disorder — Clusters A, B, & C", detail: "Class #39. Reading: Oltmanns 20, Craighead 15." },
  { course: "psyc", date: "2026-12-02", type: "reading", title: "Personality Disorder — Clusters A, B, & C (cont.)", detail: "Class #40. Reading: Craighead 14." },
  { course: "psyc", date: "2026-12-04", type: "reading", title: "Sexual Paraphilias*", detail: "Class #41. Reading: Oltmanns 22. *Potentially triggering material — attendance optional per syllabus." },
  { course: "psyc", date: "2026-12-07", type: "note", title: "Sexual Paraphilias/Review", detail: "Class #42." },
  { course: "psyc", date: "2026-12-13", type: "exam", title: "Final Exam — Finals Week (exact date TBA)", detail: "Held sometime Dec 10–16; update once the Registrar publishes the schedule." },
];

// Which events count toward the "planner" (actionable to-dos) by default
const PLANNER_TYPES = ["assignment", "exam", "reading"];
